### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by ghost** [reorr/warnai#1]
How are you? I don't follow ow this works; do you mind explained to me?
I am in I3 using lxappeariance as gtk picker

**Comment by reorr** [comment]
You need to install the dependencies first.
After that clone this repository and move to the cloned repository directory.
Now execute the following command in terminal:

`$ ./warnai -g fantome -t minima-rounded`

The `-g` flag means it will generate gtk theme, and `-t` to generate tint2 config.
If you are using pywal to generate color, run with `-w` flag, it will use pywal colorscheme. Without `-w` flag, it will read colorscheme from `.Xresources` in home folder. You could also use `-xc your/custom/.Xresource/file` to get the color scheme from certain `.Xresource` file.

**Comment by ghost** [comment]
Hi there @reorr; I am back here to ask how can i fix line 16? I am in Manjaro I3gaps.

`Generating theme ...
~/.themes/warna/gtk-2.0 ~/warnai ~/warnai
Rendering gtk2 assets
Rendering assets/button-active.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/button-hover.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/button-insensitive.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/button.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/checkbox-checked-insensitive.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/checkbox-checked.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/checkbox-unchecked-insensitive.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/checkbox-unchecked.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/combo-entry-border-focus.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/combo-entry-border-focus-rtl.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/combo-entry-border.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/combo-entry-border-rtl.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/combo-entry-button-active.png
/home/niko/.themes/warna/gtk-2.0/render-assets.sh: line 16: /usr/bin/optipng: No such file or directory                                                                                               
Rendering assets/combo-entry-button-active-rtl.png`

**Comment by reorr** [comment]
Sorry, my mistake.
I forgot to add `optipng` as a dependency, please install `optipng` package first.

**Comment by annata83** [comment]
Sure no problem. Are you referring to this: https://aur.archlinux.org/packages/optipng-hg/ ?

**Comment by ghost** [comment]
What's up @reorr Thank you for the Update.
I did what you told me and it seems it works but nothing has changed in terms of GTK Theme.
Let me Post the output for you to confirm everything is alright and if you don't mind again what sure I do next?(I have the warna selected in lxappearence and even made a copy of fantome into /usr/share/themes and try it as well, both are pain gtk themes)

`Generating theme ...
~/.themes/warna/gtk-2.0 ~/warnai ~/warnai
Rendering gtk2 assets
Rendering assets/button-active.png
Rendering assets/button-hover.png
Rendering assets/button-insensitive.png
Rendering assets/button.png
Rendering assets/checkbox-checked-insensitive.png
Rendering assets/checkbox-checked.png
Rendering assets/checkbox-unchecked-insensitive.png
Rendering assets/checkbox-unchecked.png
Rendering assets/combo-entry-border-focus.png
Rendering assets/combo-entry-border-focus-rtl.png
Rendering assets/combo-entry-border.png
Rendering assets/combo-entry-border-rtl.png
Rendering assets/combo-entry-button-active.png
Rendering assets/combo-entry-button-active-rtl.png
Rendering assets/combo-entry-button-insensitive.png
Rendering assets/combo-entry-button-insensitive-rtl.png
Rendering assets/combo-entry-button.png
Rendering assets/combo-entry-button-rtl.png
Rendering assets/combo-entry-focus-notebook.png
Rendering assets/combo-entry-focus-notebook-rtl.png
Rendering assets/combo-entry-focus.png
Rendering assets/combo-entry-focus-rtl.png
Rendering assets/combo-entry-insensitive-notebook.png
Rendering assets/combo-entry-insensitive-notebook-rtl.png
Rendering assets/combo-entry-insensitive.png
Rendering assets/combo-entry-insensitive-rtl.png
Rendering assets/combo-entry-notebook.png
Rendering assets/combo-entry-notebook-rtl.png
Rendering assets/combo-entry.png
Rendering assets/combo-entry-rtl.png
Rendering assets/down-background-disable.png
Rendering assets/down-background-disable-rtl.png
Rendering assets/down-background.png
Rendering assets/down-background-rtl.png
Rendering assets/entry-active-bg.png
Rendering assets/entry-active-notebook.png
Rendering assets/entry-active-toolbar.png
Rendering assets/entry-background-disabled.png
Rendering assets/entry-background.png
Rendering assets/entry-bg.png
Rendering assets/entry-border-active-bg.png
Rendering assets/entry-border-bg.png
Rendering assets/entry-disabled-bg.png
Rendering assets/entry-disabled-notebook.png
Rendering assets/entry-disabled-toolbar.png
Rendering assets/entry-notebook.png
Rendering assets/entry-toolbar.png
Rendering assets/focus-line.png
Rendering assets/frame-gap-end.png
Rendering assets/frame-gap-start.png
Rendering assets/frame.png
Rendering assets/handle-h.png
Rendering assets/handle-v.png
Rendering assets/inline-toolbar.png
Rendering assets/line-h.png
Rendering assets/line-v.png
Rendering assets/listasset.txt.png

** (inkscape:23417): WARNING **: 01:13:57.691: Object with id="listasset.txt" was not found in the document. Nothing exported.
Rendering assets/menu-arrow.png
Rendering assets/menu-arrow-prelight.png
Rendering assets/menubar_button.png
Rendering assets/menubar.png
Rendering assets/menu-checkbox-checked-insensitive.png
Rendering assets/menu-checkbox-checked.png
Rendering assets/menu-checkbox-checked-selected.png
Rendering assets/menu-checkbox-unchecked-insensitive.png
Rendering assets/menu-checkbox-unchecked.png
Rendering assets/menu-checkbox-unchecked-selected.png
Rendering assets/menuitem.png
Rendering assets/menu-radio-checked-insensitive.png
Rendering assets/menu-radio-checked.png
Rendering assets/menu-radio-checked-selected.png
Rendering assets/menu-radio-unchecked-insensitive.png
Rendering assets/menu-radio-unchecked.png
Rendering assets/menu-radio-unchecked-selected.png
Rendering assets/minus.png
Rendering assets/notebook-gap-horiz.png
Rendering assets/notebook-gap-vert.png
Rendering assets/notebook.png
Rendering assets/null.png
Rendering assets/plus.png
Rendering assets/progressbar.png
Rendering assets/progressbar_v.png
Rendering assets/radio-checked-insensitive.png
Rendering assets/radio-checked.png
Rendering assets/radio-unchecked-insensitive.png
Rendering assets/radio-unchecked.png
Rendering assets/slider-horiz-active.png
Rendering assets/slider-horiz-insens.png
Rendering assets/slider-horiz.png
Rendering assets/slider-horiz-prelight.png
Rendering assets/slider-insensitive.png
Rendering assets/slider.png
Rendering assets/slider-prelight.png
Rendering assets/slider-vert-active.png
Rendering assets/slider-vert-insens.png
Rendering assets/slider-vert.png
Rendering assets/slider-vert-prelight.png
Rendering assets/tab-bottom-active.png
Rendering assets/tab-left-active.png
Rendering assets/tab-right-active.png
Rendering assets/tab-top-active.png
Rendering assets/toolbar.png
Rendering assets/tree_header.png
Rendering assets/trough-horizontal-active.png
Rendering assets/trough-horizontal.png
Rendering assets/trough-progressbar.png
Rendering assets/trough-progressbar_v.png
Rendering assets/trough-scrollbar-horiz.png
Rendering assets/trough-scrollbar-vert.png
Rendering assets/trough-vertical-active.png
Rendering assets/trough-vertical.png
Rendering assets/up-background-disable.png
Rendering assets/up-background-disable-rtl.png
Rendering assets/up-background.png
Rendering assets/up-background-rtl.png
~/warnai ~/warnai
~/.themes/warna/gtk-3.0 ~/warnai ~/warnai
Rendering gtk3 assets
Rendering assets/checkbox-checked.png
Rendering assets/checkbox-checked@2.png
Rendering assets/checkbox-checked-insensitive.png
Rendering assets/checkbox-checked-insensitive@2.png
Rendering assets/checkbox-unchecked.png
Rendering assets/checkbox-unchecked@2.png
Rendering assets/checkbox-unchecked-insensitive.png
Rendering assets/checkbox-unchecked-insensitive@2.png
Rendering assets/checkbox-mixed.png
Rendering assets/checkbox-mixed@2.png
Rendering assets/checkbox-mixed-insensitive.png
Rendering assets/checkbox-mixed-insensitive@2.png
Rendering assets/radio-checked.png
Rendering assets/radio-checked@2.png
Rendering assets/radio-checked-insensitive.png
Rendering assets/radio-checked-insensitive@2.png
Rendering assets/radio-unchecked.png
Rendering assets/radio-unchecked@2.png
Rendering assets/radio-unchecked-insensitive.png
Rendering assets/radio-unchecked-insensitive@2.png
Rendering assets/radio-mixed.png
Rendering assets/radio-mixed@2.png
Rendering assets/radio-mixed-insensitive.png
Rendering assets/radio-mixed-insensitive@2.png
Rendering assets/checkbox-checked-selected.png
Rendering assets/checkbox-checked-selected@2.png
Rendering assets/checkbox-checked-insensitive-selected.png
Rendering assets/checkbox-checked-insensitive-selected@2.png
Rendering assets/checkbox-unchecked-selected.png
Rendering assets/checkbox-unchecked-selected@2.png
Rendering assets/checkbox-unchecked-insensitive-selected.png
Rendering assets/checkbox-unchecked-insensitive-selected@2.png
Rendering assets/checkbox-mixed-selected.png
Rendering assets/checkbox-mixed-selected@2.png
Rendering assets/checkbox-mixed-insensitive-selected.png
Rendering assets/checkbox-mixed-insensitive-selected@2.png
Rendering assets/checkbox-checked-selectionmode.png
Rendering assets/checkbox-checked-selectionmode@2.png
Rendering assets/checkbox-selectionmode.png
Rendering assets/checkbox-selectionmode@2.png
Rendering assets/radio-checked-selected.png
Rendering assets/radio-checked-selected@2.png
Rendering assets/radio-checked-insensitive-selected.png
Rendering assets/radio-checked-insensitive-selected@2.png
Rendering assets/radio-unchecked-selected.png
Rendering assets/radio-unchecked-selected@2.png
Rendering assets/radio-unchecked-insensitive-selected.png
Rendering assets/radio-unchecked-insensitive-selected@2.png
Rendering assets/radio-mixed-selected.png
Rendering assets/radio-mixed-selected@2.png
Rendering assets/radio-mixed-insensitive-selected.png
Rendering assets/radio-mixed-insensitive-selected@2.png
Rendering assets/switch.png
Rendering assets/switch@2.png
Rendering assets/switch-active.png
Rendering assets/switch-active@2.png
Rendering assets/switch-insensitive.png
Rendering assets/switch-insensitive@2.png
Rendering assets/switch-active-insensitive.png
Rendering assets/switch-active-insensitive@2.png
Rendering assets/switch-header.png
Rendering assets/switch-header@2.png
Rendering assets/switch-active-header.png
Rendering assets/switch-active-header@2.png
Rendering assets/switch-insensitive-header.png
Rendering assets/switch-insensitive-header@2.png
Rendering assets/switch-active-insensitive-header.png
Rendering assets/switch-active-insensitive-header@2.png
Rendering assets/switch-selected.png
Rendering assets/switch-selected@2.png
Rendering assets/switch-active-selected.png
Rendering assets/switch-active-selected@2.png
Rendering assets/switch-insensitive-selected.png
Rendering assets/switch-insensitive-selected@2.png
Rendering assets/switch-active-insensitive-selected.png
Rendering assets/switch-active-insensitive-selected@2.png
Rendering assets/titlebutton-close.png
Rendering assets/titlebutton-close@2.png
Rendering assets/titlebutton-close-backdrop.png
Rendering assets/titlebutton-close-backdrop@2.png
Rendering assets/titlebutton-close-hover.png
Rendering assets/titlebutton-close-hover@2.png
Rendering assets/titlebutton-close-active.png
Rendering assets/titlebutton-close-active@2.png
Rendering assets/titlebutton-maximize.png
Rendering assets/titlebutton-maximize@2.png
Rendering assets/titlebutton-maximize-backdrop.png
Rendering assets/titlebutton-maximize-backdrop@2.png
Rendering assets/titlebutton-maximize-hover.png
Rendering assets/titlebutton-maximize-hover@2.png
Rendering assets/titlebutton-maximize-active.png
Rendering assets/titlebutton-maximize-active@2.png
Rendering assets/titlebutton-minimize.png
Rendering assets/titlebutton-minimize@2.png
Rendering assets/titlebutton-minimize-backdrop.png
Rendering assets/titlebutton-minimize-backdrop@2.png
Rendering assets/titlebutton-minimize-hover.png
Rendering assets/titlebutton-minimize-hover@2.png
Rendering assets/titlebutton-minimize-active.png
Rendering assets/titlebutton-minimize-active@2.png
Rendering assets/checkbox-checked-dark.png
Rendering assets/checkbox-checked-dark@2.png
Rendering assets/checkbox-checked-insensitive-dark.png
Rendering assets/checkbox-checked-insensitive-dark@2.png
Rendering assets/checkbox-unchecked-dark.png
Rendering assets/checkbox-unchecked-dark@2.png
Rendering assets/checkbox-unchecked-insensitive-dark.png
Rendering assets/checkbox-unchecked-insensitive-dark@2.png
Rendering assets/checkbox-mixed-dark.png
Rendering assets/checkbox-mixed-dark@2.png
Rendering assets/checkbox-mixed-insensitive-dark.png
Rendering assets/checkbox-mixed-insensitive-dark@2.png
Rendering assets/checkbox-checked-selectionmode-dark.png
Rendering assets/checkbox-checked-selectionmode-dark@2.png
Rendering assets/checkbox-selectionmode-dark.png
Rendering assets/checkbox-selectionmode-dark@2.png
Rendering assets/radio-checked-dark.png
Rendering assets/radio-checked-dark@2.png
Rendering assets/radio-checked-insensitive-dark.png
Rendering assets/radio-checked-insensitive-dark@2.png
Rendering assets/radio-unchecked-dark.png
Rendering assets/radio-unchecked-dark@2.png
Rendering assets/radio-unchecked-insensitive-dark.png
Rendering assets/radio-unchecked-insensitive-dark@2.png
Rendering assets/radio-mixed-dark.png
Rendering assets/radio-mixed-dark@2.png
Rendering assets/radio-mixed-insensitive-dark.png
Rendering assets/radio-mixed-insensitive-dark@2.png
Rendering assets/switch-dark.png
Rendering assets/switch-dark@2.png
Rendering assets/switch-active-dark.png
Rendering assets/switch-active-dark@2.png
Rendering assets/switch-insensitive-dark.png
Rendering assets/switch-insensitive-dark@2.png
Rendering assets/switch-active-insensitive-dark.png
Rendering assets/switch-active-insensitive-dark@2.png
Rendering assets/switch-header-dark.png
Rendering assets/switch-header-dark@2.png
Rendering assets/switch-active-header-dark.png
Rendering assets/switch-active-header-dark@2.png
Rendering assets/switch-insensitive-header-dark.png
Rendering assets/switch-insensitive-header-dark@2.png
Rendering assets/switch-active-insensitive-header-dark.png
Rendering assets/switch-active-insensitive-header-dark@2.png
Rendering assets/titlebutton-close-dark.png
Rendering assets/titlebutton-close-dark@2.png
Rendering assets/titlebutton-close-backdrop-dark.png
Rendering assets/titlebutton-close-backdrop-dark@2.png
Rendering assets/titlebutton-close-hover-dark.png
Rendering assets/titlebutton-close-hover-dark@2.png
Rendering assets/titlebutton-close-active-dark.png
Rendering assets/titlebutton-close-active-dark@2.png
Rendering assets/titlebutton-maximize-dark.png
Rendering assets/titlebutton-maximize-dark@2.png
Rendering assets/titlebutton-maximize-backdrop-dark.png
Rendering assets/titlebutton-maximize-backdrop-dark@2.png
Rendering assets/titlebutton-maximize-hover-dark.png
Rendering assets/titlebutton-maximize-hover-dark@2.png
Rendering assets/titlebutton-maximize-active-dark.png
Rendering assets/titlebutton-maximize-active-dark@2.png
Rendering assets/titlebutton-minimize-dark.png
Rendering assets/titlebutton-minimize-dark@2.png
Rendering assets/titlebutton-minimize-backdrop-dark.png
Rendering assets/titlebutton-minimize-backdrop-dark@2.png
Rendering assets/titlebutton-minimize-hover-dark.png
Rendering assets/titlebutton-minimize-hover-dark@2.png
Rendering assets/titlebutton-minimize-active-dark.png
Rendering assets/titlebutton-minimize-active-dark@2.png
~/warnai ~/warnai
Applying theme ...
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Done`

**Comment by reorr** [comment]
It seems the theme has generated successfully, but xfconf-query couldn't set the theme properly in i3wm. You can change your gtk theme from `lxappearance`.

**Comment by ghost** [comment]
Hey @reorr; actually I did and also copy the fantome from warnai into usr/share/themes and try that as well but gtk2 apps don't get any changes. gtk3 app gets some modifications but not very well. Let me know if you want to keep trying to make it work I don't want to bother you with this.

**Comment by reorr** [comment]
If you just copy and paste the `fantome` folder inside the gtk folder into `/usr/themes/` or `~/.themes` it will not work, because the color has not yet defined. The way warnai works is to grab color from `.Xresources` file and parse that to other config and copy it to user specified folder. In the case with gtk theme, it will make warna folder inside `~/.themes` directory. If the run of warnai completed without error, you should see `warna` listed as gtk theme  in lxappearance.
It doesn't bother me, let me know if you still run into a problem.

**Comment by ghost** [comment]
Sure. warna is inside lxappearance and I think I clarify that I try using that and also try fantome as well with the same results. Honestly, I like to make work but don't know how to debug what's going on! if like like tell me what to do.

**Comment by reorr** [comment]
Let me ask this. Are you generate the theme using `.Xresources` file or using pywal to generate color-scheme?
If you are using `.Xresources` file, at least it must have configuration like this
```
*.background:   #222222

*.color0:       #222222
*.color1:       #924650
*.color2:       #666666
*.color3:       #ba9864
*.color4:       #888888
*.color5:       #4f8396
*.color6:       #777777
*.color8:       #222222
*.color7:       #c2c2b0
*.color9:       #924650
*.color10:      #666666
*.color11:      #ba9864
*.color12:      #888888
*.color13:      #4f8396
*.color14:      #777777
*.color15:      #c2c2b0
```

**Comment by ghost** [comment]
I am only typing ./warnai -g fantome

My Xresources colors:

! X colors.
! Generated by 'wal'

*foreground:        {foreground}
*background:        {background}
*.foreground:       {foreground}
*.background:       {background}


URxvt*foreground:   {foreground}
XTerm*foreground:   {foreground}

UXTerm*foreground:  {foreground}
!URxvt.background:   [85]#222D31
URxvt*background:   {background.alpha}
XTerm*background:   {background}
UXTerm*background:  {background}

URxvt*cursorColor:  {cursor}
XTerm*cursorColor:  {cursor}
UXTerm*cursorColor: {cursor}
URxvt*borderColor:  {background.alpha}

! Colors 0-15.
*.color0: {color0}
*color0:  {color0}
*.color1: {color1}
*color1:  {color1}
*.color2: {color2}
*color2:  {color2}
*.color3: {color3}
*color3:  {color3}
*.color4: {color4}
*color4:  {color4}
*.color5: {color5}
*color5:  {color5}
*.color6: {color6}
*color6:  {color6}
*.color7: {color7}
*color7:  {color7}
*.color8: {color8}
*color8:  {color8}
*.color9: {color9}
*color9:  {color9}
*.color10: {color10}
*color10:  {color10}
*.color11: {color11}
*color11:  {color11}
*.color12: {color12}
*color12:  {color12}
*.color13: {color13}
*color13:  {color13}
*.color14: {color14}
*color14:  {color14}
*.color15: {color15}
*color15:  {color15}

**Comment by reorr** [comment]
Thats just pywal template, not the real `.Xresources` file.
Anyway, if you are using pywal, you must use `-w` or `--wal` flag when running warnai.

**Comment by ghost** [comment]
ok i will try that. The color on the Xresources i created them to use pywal!
I gonna drop the full log as .txt and here is maybe something usefull "this is not included in the .txt file":

 **(inkscape:14899): WARNING **: 01:11:49.841: Object with id="listasset.txt" was not found in the document. Nothing exported.                                                                        
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option**
[warnaiOutput.txt](https://github.com/reorr/warnai/files/2790202/warnaiOutput.txt)


This is the output from ./warnai -w 

**Generating theme ...
Applying theme ...
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.                                                                            
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.                                                                            
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.                                                                        
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.                                                                        
Done**

and the same with --wal

**Generating theme ...
Applying theme ...
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Done**

By the way there are no more colors inside Xresources here:


[Xresources.txt](https://github.com/reorr/warnai/files/2790213/Xresources.txt)

**Comment by reorr** [comment]
Check if `~/.cache/wal/colors.Xresources` file exist. It's where pywal save its .Xresources color. If it's exist the use of `-w` or `--wal` flag should return no error and the theme will generated successfully.

**Comment by ghost** [comment]
The file ~/.cache/wal/colors.Xresources Exist.
This is the output from ./warnai -w

Generating theme ...
Applying theme ...
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Done

and the same with --wal

Generating theme ...
Applying theme ...
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/general/theme" does not exist on channel "xfwm4". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Property "/Net/ThemeName" does not exist on channel "xsettings". If a new property should be created, use the --create option.
Done

**Comment by ghost** [comment]
![warnainotworking](https://user-images.githubusercontent.com/18301363/51656178-cef4c980-1f7e-11e9-8dca-8b920c7d705e.png)
As you can see in the Pic no matter what color pywal uses warnai theme allwways looks the same
here is another one
![warnai2](https://user-images.githubusercontent.com/18301363/51656306-504c5c00-1f7f-11e9-9da5-19406aeb9e60.png)

**Comment by reorr** [comment]
Hmmm... I can't see where is the wrong.
Can you send me the zipped folder of warna from `~/.themes`?

**Comment by ghost** [comment]
Sure.
[warnaDebuging.zip](https://github.com/reorr/warnai/files/2790440/warnaDebuging.zip)

**Comment by reorr** [comment]
Just like i guess, the color doesn't properly replaced

I would like if you could follow the instruction below to test if warnai can get the color properly from the custom .Xresources file

1. Update your local repository with `$ git pull` command
2. Install python3 if you haven't installed it (the current master branch need python3 to generate gtk assets)
3. Copy config below and save to ~/colors
```
*.background:   #222222

*.color0:       #222222
*.color1:       #924650
*.color2:       #666666
*.color3:       #ba9864
*.color4:       #888888
*.color5:       #4f8396
*.color6:       #777777
*.color8:       #222222
*.color7:       #c2c2b0
*.color9:       #924650
*.color10:      #666666
*.color11:      #ba9864
*.color12:      #888888
*.color13:      #4f8396
*.color14:      #777777
*.color15:      #c2c2b0
```
4. run warnai with this flag
`$ ./warnai -xc ~/colors -g fantome`
5. open lxappearance and apply warna for gtk theme
6. It would looks like this
![kashatto_2019-01-24_14-04-14_562x451](https://user-images.githubusercontent.com/10528000/51660642-0005e600-1fe1-11e9-8317-9a9945749320.png)

**Comment by ghost** [comment]
Hey there @reorr getting the colors from a custom location works as you expected with the difference on the Apply button Fonts.:

![warnai3](https://user-images.githubusercontent.com/18301363/51886274-ddbbf180-236d-11e9-96b6-25bbef59a4cf.png)

Sorry on my late response by the way.
So how do suggest  I get this custom path to work with pywal?
I already try using the `.Xresources` and the colors file from `.cache/wal/colors` without success but the file ` /.cache/wal/colors.scss` works very well.

**Comment by reorr** [comment]
Well, if it works with `~/.cache/wal/colors.scss`, i dont know why it does not works with `~/.cache/wal/colors.Xresources`. It's unlikely because bug in the program, so i considering closing this issue.

**Comment by ghost** [comment]
Yeah, I was gonna closet it but was waiting on you in case you want me to do something else. 
Thanks very much for your Help and of course for the great app.
